import { Resume } from './resume'
import { SkillTypes } from './skills'
import { now } from './time'
export const resume = new Resume({
  person: {
    name: 'Bryce McLachlan',
    pronouns: 'he/him/his',
    position: 'Full Stack Software Engineer, Team Lead',
    summary:
      'Over a decade of leadership experience across a range of industries and a year of software engineering experience. I am a compassionate software engineer who is seeking their next role where they can make an impact.',
    contactInfo: {
      email: new URL('mailto:brycemclachlan@gmail.com'),
      github: new URL('https://github.com/brycemcl'),
      linkedIn: new URL('https://linkedin.com/in/bryce-mclachlan'),
      phoneNumber: new URL('tel:6043005727'),
    },
  },
  skills: [
    // { name: 'AWS IoT Core(MQTT)', type: SkillTypes.Protocols },
    // { name: 'AMQP', type: SkillTypes.Protocols },
    // { name: 'Kafka', type: SkillTypes.Protocols },
    // { name: 'HTTP', type: SkillTypes.Protocols },
    // { name: 'SOAP', type: SkillTypes.Protocols },
    // { name: 'REST', type: SkillTypes.Protocols },
    { name: 'Javascript', type: SkillTypes.Languages },
    { name: 'Typescript', type: SkillTypes.Languages },
    // { name: 'Bash', type: SkillTypes.Languages },
    // { name: 'HTML', type: SkillTypes.Languages },
    // { name: 'CSS', type: SkillTypes.Languages },
    { name: 'SQL', type: SkillTypes.Languages },
    // { name: 'JSON', type: SkillTypes.Languages },
    { name: 'Protocol Buffers', type: SkillTypes.Languages },
    { name: 'MJML', type: SkillTypes.Languages },
    { name: 'GraphQL', type: SkillTypes.Languages },
    { name: 'Express', type: SkillTypes.Frameworks },
    { name: 'NestJS', type: SkillTypes.Frameworks },
    // { name: 'TailwindCSS', type: SkillTypes.Frameworks },
    { name: 'Angular', type: SkillTypes.Frameworks },
    // { name: 'Next.js', type: SkillTypes.Frameworks },
    // { name: 'Mongoose', type: SkillTypes.Libraries },
    { name: 'Prisma', type: SkillTypes.Libraries },
    { name: 'React', type: SkillTypes.Libraries },
    // { name: 'Axios', type: SkillTypes.Libraries },
    // { name: 'RxJS', type: SkillTypes.Libraries },
    // { name: 'styled-components', type: SkillTypes.Libraries },
    { name: 'Puppeteer', type: SkillTypes.Testing },
    // { name: 'Playwright', type: SkillTypes.Testing },
    { name: 'Client Side(Web Browsers)', type: SkillTypes.Environments },
    {
      name: 'Serverless(AWS Lambda & Firebase Cloud Functions)',
      type: SkillTypes.Environments,
    },
    {
      name: 'Containers(Docker, ECS & Kubernetes)',
      type: SkillTypes.Environments,
    },
    { name: 'Virtual Machines(KVM, EC2 & DO)', type: SkillTypes.Environments },
    { name: 'Bare Metal(MAAS)', type: SkillTypes.Environments },
    { name: 'PostgreSQL/AWS Aurora', type: SkillTypes.Storage },
    { name: 'Redshift', type: SkillTypes.Storage },
    { name: 'DocumentDB/MongoDB', type: SkillTypes.Storage },
    { name: 'AWS S3', type: SkillTypes.Storage },
    // { name: 'Backblaze B2', type: SkillTypes.Storage },
    // { name: 'Ceph-Rook(Block)', type: SkillTypes.Storage },
    // {
    //   name: 'NAS (Samba running on a on-prem Kubernetes cluster)',
    //   type: SkillTypes.Storage,
    // },
    { name: 'OpenAPI', type: SkillTypes.Tools },
    // { name: 'NPM', type: SkillTypes.Tools },
    // { name: 'NPX', type: SkillTypes.Tools },
    // { name: 'Babel', type: SkillTypes.Tools },
    // { name: 'PostCSS', type: SkillTypes.Tools },
    // { name: 'Webpack', type: SkillTypes.Tools },
    { name: 'Docker', type: SkillTypes.Tools },
    { name: 'Kubectl', type: SkillTypes.Tools },
    // { name: 'Postman', type: SkillTypes.Tools },
    // { name: 'Slack', type: SkillTypes.Tools },
    // { name: 'Jira', type: SkillTypes.Tools },
    // { name: 'Confluence', type: SkillTypes.Tools },
    { name: 'Terraform', type: SkillTypes.Tools },
    { name: 'Git', type: SkillTypes.Tools },
    // { name: 'GitHub Actions', type: SkillTypes.Tools },
    { name: 'GitLab CI/CD', type: SkillTypes.Tools },
    // { name: 'Mocha', type: SkillTypes.Testing },
    // { name: 'Chai', type: SkillTypes.Testing },
    { name: 'Jest', type: SkillTypes.Testing },
    // { name: 'Cypress', type: SkillTypes.Testing },
    // { name: 'Puppeteer', type: SkillTypes.Testing },
    // { name: 'Playwright', type: SkillTypes.Testing },
    // { name: 'XState', type: SkillTypes.Testing },
    { name: 'OpenTelemetry', type: SkillTypes.Monitoring },
    { name: 'AWS CloudWatch', type: SkillTypes.Monitoring },
    // { name: 'Prometheus', type: SkillTypes.Monitoring },
    { name: 'Zipkin', type: SkillTypes.Monitoring },
  ],
  experience: [
    {
      dateStart: new Date('2022-02'),
      dateEnd: now,
      organization: 'Fobi AI',
      position: 'Full Stack Software Engineer, Team Lead',
      summary:
        'Lead a refactor of an existing codebase to migrate from a NoSQL database to a SQL database, implemented type safety across our codebase/apis and implemented custom autoscaling metrics.\n\nHelp balance the competing priorities of various stakeholders, provide mentorship to teammates and lead discussions regarding both company culture and technical topics.',
    },
    {
      dateStart: new Date('2021-05'),
      dateEnd: new Date('2022-02'),
      organization: 'Fobi AI',
      position: 'Full Stack Software Engineer',
      summary:
        'Working in a scrum team, develop our analytics platform to support custom use cases, improve reliability, reduce costs and add new features.',
    },
    {
      dateStart: new Date('2016-06'),
      dateEnd: new Date('2020-11'),
      organization: 'JCR Design & Drafting',
      position: 'Building Designer',
      summary:
        'Designed and configured our network at our new office. Implemented Kubernetes cluster that hosted our NAS, remote access and 3d rendering jobs. Performed system administration for our IT systems. Scripted away repetitive parts of the designing buildings.\n\nCore responsibilities include mentorship for new designers, reviewing drawings before submissions, coordination between involved parties and designing buildings.',
    },
  ],
  projects: [
    // {
    //   name: 'This resume you are looking at',
    //   date: new Date('2021-04'),
    //   stack: ['React', 'Playwright', 'Typescript'],
    //   summary:
    //     'Using React as a template engine, this resume shows how web technologies can be used outside a browser context. I have applied a similar concept for dynamically creating emails with MJML and React in a production applicion.',
    //   github: new URL('https://github.com/brycemcl/resume'),
    //   liveDemo: new URL('https://brycemcl.github.io/resume/'),
    //   callToAction: 'Updated PDF',
    // },
  ],
  education: [
    {
      dateStart: new Date('2021'),
      dateEnd: new Date('2021'),
      organization: 'Lighthouse Labs',
      position: 'Web Development Diploma',
      summary:
        'Learned practical skills to use web technologies to build modern websites, apps, & tools.',
    },
    {
      dateStart: new Date('2015'),
      dateEnd: new Date('2016'),
      organization: 'University of the Fraser Valley',
      position: 'Architectural Drafting Certificate',
      summary:
        'Developed skills to design buildings, write technical documents & navigate the legal frameworks regulating the building industry.',
    },
    {
      dateStart: new Date('2014'),
      dateEnd: new Date('2015'),
      organization: 'University of the Fraser Valley',
      position: 'Computer & information Systems Studies',
      summary:
        'Developed foundational skills to integrate information technologies into a business.',
    },
  ],
})
